#!/usr/bin/env python3
"""Generate the ECMAScript conformance tables of luce_regex.regex from luce-js's libregexp port.

usage: tools/oracle_tables.py LUCE_JS_REGEXP_MODULE_DIR

The rows of the libregexp port's generated tables (tests_compile_table*.lucb,
tests_exec_table*.lucb, tests_escape_table.lucb, printed by a C driver linked with upstream
QuickJS libregexp.c) are rewritten as es_table_*.lucb fragments of src/luce_regex/regex/.
A compile row keeps its outcome: the error message, or the capture count, flags and group
names (the bytecode bytes, length and register count are libregexp's own and are dropped).
Exec and escape rows are kept as they are.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/luce_regex/regex"
SRC = Path(sys.argv[1])

HEADER = """#==============================================================================================
#
#   {name} - {title}
#
#   DESCRIPTION:
#       Generated by tools/oracle_tables.py, do not edit: rows of luce-js's libregexp port
#       tests, printed by a C driver linked with QuickJS libregexp.c, libunicode.c and
#       cutils.c (2026-06-04). {what}
#
#==============================================================================================

"""


def rows(path, kind):
    text = path.read_text()
    body = text[text.index("= [") + 3:text.rindex("]")]
    # each row is Kind(...), possibly over two lines
    items = re.findall(kind + r"\((.*?)\),\n", body, re.S)
    return [" ".join(line.strip() for line in item.split("\n")).strip() for item in items]


def compile_row(item):
    # "pattern", flags, mode, "expect"
    m = re.match(r'(".*"), (\d+), (\d+),\s+"(.*)"$', item, re.S)
    pattern, flags, mode, expect = m.groups()
    if expect.startswith("ok"):
        cc = re.search(r"cc=(\d+)", expect).group(1)
        fl = re.search(r"flags=(0x[0-9a-f]+)", expect).group(1)
        names = re.search(r"names=(\S+)", expect)
        expect = f"ok cc={cc} flags={fl}" + (f" names={names.group(1)}" if names else "")
    return f'    CompileCase({pattern}, {flags}, {mode}, "{expect}"),'


def write(name, title, what, decl, lines):
    text = HEADER.format(name=name, title=title, what=what)
    text += f"let {decl}[{len(lines)}] = [\n" + "\n".join(lines) + "\n]\n"
    (OUT / f"{name}.lucb").write_text(text)


compile_rows = []
for part in (1, 2):
    compile_rows += [compile_row(i) for i in rows(SRC / f"tests_compile_table{part}.lucb", "CompileCase")]
write("es_table_compile", "Expected compile results", "Each row is a pattern, its flags, a host\n#       mode (see es_tests.lucb) and its outcome.",
      "es_compile_cases: CompileCase", compile_rows)

for part in (1, 2):
    exec_rows = ["    ExecCase(" + i + ")," for i in rows(SRC / f"tests_exec_table{part}.lucb", "ExecCase")]
    write(f"es_table_exec{part}", f"Expected exec results (part {part})",
          "Each row is a pattern, its flags, a host\n#       mode, the subject (%XXXX is a code unit in hex), 0 for an 8-bit or 1 for a 16-bit\n#       subject, the start index and the result.",
          f"es_exec_cases{part}: ExecCase", exec_rows)

escape_rows = ["    EscapeCase(" + i + ")," for i in rows(SRC / "tests_escape_table.lucb", "EscapeCase")]
write("es_table_escape", "Expected parse_escape results", "Each row is the text after the backslash,\n#       allow_utf16, and the result and the number of bytes consumed.",
      "es_escape_cases: EscapeCase", escape_rows)
